INSERT INTO USER_DIM VALUES (1,'Aaron','Nunc.commodo@risusa.edu','M','11-Sep-2009','65335','Ajaccio','France','Europe','NONE','XIAOMI');
INSERT INTO USER_DIM VALUES (2,'Benjamin','tincidunt@liberoMorbiaccumsan.org','M','18-Dec-1996','64798','Berlin','Germany','Europe','NONE','SONY');
INSERT INTO USER_DIM VALUES (3,'Marlon','volutpat.nunc.sit@eratsemperrutrum.com','M','17-Jul-1969','996563','Calama','Chile','South-America','MASTERCARD','BLACKBERRY');
INSERT INTO USER_DIM VALUES (4,'Tanya','sit.amet@semperauctor.co.uk','F','01-Oct-2000','ZY9M 2FJ','Kingussie','United Kingdom','Europe','MASTERCARD','DORO');
INSERT INTO USER_DIM VALUES (5,'Jana','cursus.Nunc@mollisDuissit.co.uk','M','06-Jun-1969','64144','Emden','Germany','Europe','GIFT CARD','HUAWEI');
INSERT INTO USER_DIM VALUES (6,'Fallon','ante.blandit@NullamnislMaecenas.net','F','21-Aug-1967','133372','Sapele','Nigeria','Africa','MASTERCARD','WIKO');
INSERT INTO USER_DIM VALUES (7,'Leonardo','sed@mitempor.ca','F','24-Jan-1984','523981','Cabo de Hornos','Chile','South-America','MASTERCARD','XIAOMI');
INSERT INTO USER_DIM VALUES (8,'Dimitri','Quisque@Nuncmauriselit.co.uk','F','04-Sep-1971','68714','Saint-Sébastien-sur-Loire','France','Pays de la Loire','MASTERCARD','ALCATEL');
INSERT INTO USER_DIM VALUES (9,'Audra','id@pellentesquemassalobortis.edu','F','29-Jul-1967','T2W 0A2','Barrhead','Canada','Alberta','GIFT CARD','XIAOMI');
INSERT INTO USER_DIM VALUES (10,'Keiko','aliquet.libero.Integer@ultriciessem.ca','F','27-Nov-1997','84383-038','Ponta Grossa','Brazil','Paraná','GIFT CARD','NOKIA');
INSERT INTO USER_DIM VALUES (11,'Cody','ac.arcu@In.net','F','01-May-1985','7195','Seilles','Belgium','Namen','NONE','MOTOROLA');
INSERT INTO USER_DIM VALUES (12,'Olga','non@risusDonecegestas.ca','F','15-Jul-1993','4058','Sijsele','Belgium','West-Vlaanderen','VISA','NOKIA');
INSERT INTO USER_DIM VALUES (13,'Henry','magnis.dis.parturient@quamelementum.net','F','22-Dec-1978','64502','Gelsenkirchen','Germany','NW','GIFT CARD','NONE');
INSERT INTO USER_DIM VALUES (14,'Maria','purus.accumsan@natoque.com','F','28-Sep-1991','72033','Falun','Sweden','W','VISA','MEIZU');
INSERT INTO USER_DIM VALUES (15,'Teagan','magna.Suspendisse@indolorFusce.net','F','02-Feb-1988','XF83 7RT','Beaumaris','United Kingdom','Anglesey','MASTERCARD','HONOR');
INSERT INTO USER_DIM VALUES (16,'Alexis','nisl.elementum@erategettincidunt.com','F','20-Jun-1996','28554','Wichita','United States','KS','MASTERCARD','NONE');
INSERT INTO USER_DIM VALUES (17,'Martin','elementum.lorem@eunequepellentesque.edu','M','11-Dec-1991','28491','Dieppe','France','Haute-Normandie','AMERICAN EXPRESS','NONE');
INSERT INTO USER_DIM VALUES (18,'Alec','hendrerit.neque@magnaSedeu.net','M','14-Aug-1966','JR22 2LK','Rochester','United Kingdom','KE','MASTERCARD','DORO');
INSERT INTO USER_DIM VALUES (19,'Germane','lectus.pede@sedtortor.edu','M','06-Apr-1978','9071','Laakdal','Belgium','Antwerpen','NONE','ALCATEL');
INSERT INTO USER_DIM VALUES (20,'Tanisha','euismod.mauris.eu@loremac.edu','M','27-Jan-1967','TB6 6RJ','Bodmin','United Kingdom','CO','GIFT CARD','MOTOROLA');
INSERT INTO USER_DIM VALUES (21,'Delilah','ornare@scelerisquedui.co.uk','F','16-Sep-1966','7834','Haren','Belgium','BU','NONE','ASUS');
INSERT INTO USER_DIM VALUES (22,'Germane','enim.nec.tempus@Nullamfeugiat.com','M','04-Jul-1986','4245','Chastre','Belgium','WB','AMERICAN EXPRESS','BLACKBERRY');
INSERT INTO USER_DIM VALUES (23,'Jade','at@enim.ca','M','30-Dec-1983','37047','Vandoeuvre-lès-Nancy','France','Lorraine','GIFT CARD','WIKO');
INSERT INTO USER_DIM VALUES (24,'Alfonso','id.mollis@eulacus.edu','M','17-Jul-1985','60186','Rock Springs','United States','Wyoming','NONE','HTC');
INSERT INTO USER_DIM VALUES (25,'Adrien','mattis.ornare.lectus@Nam.com','F','06-Jun-2006','36902','Forbach','France','Lorraine','AMERICAN EXPRESS','CONDOR');
INSERT INTO USER_DIM VALUES (26,'Nomlanga','ut@sit.co.uk','M','17-Feb-2006','F43 8UR','Margate','United Kingdom','KE','VISA','DORO');
INSERT INTO USER_DIM VALUES (27,'Aldair','est.ac.mattis@tortorNunccommodo.ca','M','27-Sep-1964','291251','Ñuñoa','Chile','RM','AMERICAN EXPRESS','CONDOR');
INSERT INTO USER_DIM VALUES (28,'Rammohan','cursus@porttitortellus.com','M','04-Jul-1992','870003','Agartala','India','Tripura','NONE','WIKO');
INSERT INTO USER_DIM VALUES (29,'Sandra','sollicitudin.a.malesuada@acturpis.net','M','09-Apr-2008','643666','Ijebu Ode','Nigeria','Ogun','MASTERCARD','DORO');
INSERT INTO USER_DIM VALUES (30,'Malcolm','dictum.eu.placerat@duinecurna.net','M','20-Nov-1979','50318','Nicoya','Costa Rica','G','MASTERCARD','NOKIA');
INSERT INTO USER_DIM VALUES (31,'Jolene','sit.amet.consectetuer@Nam.co.uk','F','30-Aug-1968','84126','Waren','Germany','Mecklenburg-Vorpommern','NONE','MOTOROLA');
INSERT INTO USER_DIM VALUES (32,'Nicholas','et.eros.Proin@metus.edu','M','22-Apr-2007','55862','Kapolei','United States','HI','NONE','BQ');
INSERT INTO USER_DIM VALUES (33,'August','facilisis.facilisis.magna@elit.net','M','10-Mar-1992','00625','Bremerhaven','Germany','Bremen','NONE','BQ');
INSERT INTO USER_DIM VALUES (34,'Martha','Aenean@ullamcorperviverra.org','F','15-Apr-1991','95748','Meißen','Germany','Saxony','VISA','CROSSCALL');
INSERT INTO USER_DIM VALUES (35,'Sajal','Nunc@imperdietullamcorper.ca','F','21-Feb-1967','114767','Gangtok','India','Sikkim','MASTERCARD','NOKIA');
INSERT INTO USER_DIM VALUES (36,'Jameson','mauris.id@sitamet.edu','F','30-Dec-2007','X2B 6P0','Gjoa Haven','Canada','Nunavut','MASTERCARD','LG');
INSERT INTO USER_DIM VALUES (37,'Luna','massa.Suspendisse.eleifend@anteMaecenas.ca','F','26-Aug-2001','96218','Rodez','France','Midi-Pyrénées','AMERICAN EXPRESS','MOTOROLA');
INSERT INTO USER_DIM VALUES (38,'Gisela','Aliquam.adipiscing.lobortis@Integer.net','F','13-Jan-1989','3594','Steendorp','Belgium','Oost-Vlaanderen','MASTERCARD','MOTOROLA');
INSERT INTO USER_DIM VALUES (39,'Anna','ornare.sagittis@tortorInteger.co.uk','M','24-Jan-1976','99229','Lidköping','Sweden','Västra Götalands län','NONE','NOKIA');
INSERT INTO USER_DIM VALUES (40,'Karina','dolor.Nulla@Sedpharetra.org','M','08-Mar-2000','405655','Awka','Nigeria','AN','GIFT CARD','IPHONE');
INSERT INTO USER_DIM VALUES (41,'Amena','euismod@convallisin.co.uk','F','13-Apr-1984','85122','Louisville','United States','Kentucky','MASTERCARD','ARCHOS');
INSERT INTO USER_DIM VALUES (42,'Jailekha','adipiscing.enim.mi@lobortisauguescelerisque.ca','F','08-Mar-1989','632379','Faridabad','India','HR','MASTERCARD','LG');
INSERT INTO USER_DIM VALUES (43,'Vance','vehicula.Pellentesque@acfermentum.ca','F','05-Jul-1997','19240','Honolulu','United States','HI','VISA','ASUS');
INSERT INTO USER_DIM VALUES (44,'Sigourney','id.ante@eudui.ca','M','30-Aug-2006','24228','Melilla','Spain','Melilla','VISA','ZTE');
INSERT INTO USER_DIM VALUES (45,'Nero','enim.non@ut.ca','M','04-Jun-1974','279255','Okigwe','Nigeria','Imo','AMERICAN EXPRESS','ASUS');
INSERT INTO USER_DIM VALUES (46,'Chanyana','sed@ante.edu','F','08-Sep-1983','824594','Daman','India','Daman and Diu','MASTERCARD','HUAWEI');
INSERT INTO USER_DIM VALUES (47,'Maxence','lacus@euarcuMorbi.org','M','16-Apr-1990','69214','Rennes','France','Bretagne','AMERICAN EXPRESS','ALCATEL');
INSERT INTO USER_DIM VALUES (48,'Emerson','Integer.id.magna@enim.ca','F','02-Nov-1990','70467','Ribnitz-Damgarten','Germany','Mecklenburg-Vorpommern','VISA','ZTE');
INSERT INTO USER_DIM VALUES (49,'Francesco','interdum.ligula@quis.net','F','21-Nov-2008','706096','Taltal','Chile','II','NONE','SAMSUNG');
INSERT INTO USER_DIM VALUES (50,'Madonna','consectetuer.adipiscing.elit@posuereat.edu','M','18-Nov-1965','44162','San Cristóbal de la Laguna','Spain','CN','AMERICAN EXPRESS','XIAOMI');
INSERT INTO USER_DIM VALUES (51,'Ignacia','laoreet.posuere.enim@at.net','M','06-Dec-1993','383208','Lagos','Nigeria','LA','GIFT CARD','ARCHOS');
INSERT INTO USER_DIM VALUES (52,'Daniel','molestie.orci@sedestNunc.edu','F','19-Dec-2008','L3X 3EF','Kirkintilloch','United Kingdom','Dunbartonshire','AMERICAN EXPRESS','ALCATEL');
INSERT INTO USER_DIM VALUES (53,'Panchanan','neque.In.ornare@dolor.co.uk','F','16-Jan-1990','613469','Aizwal','India','MZ','GIFT CARD','DORO');
INSERT INTO USER_DIM VALUES (54,'Ahmed','lobortis@Maecenasmifelis.ca','F','14-May-1992','73775-474','Anápolis','Brazil','Goiás','GIFT CARD','LG');
INSERT INTO USER_DIM VALUES (55,'Celeste','Proin.sed@erateget.co.uk','M','17-Apr-2002','75113','Görlitz','Germany','Saxony','VISA','NOKIA');
INSERT INTO USER_DIM VALUES (56,'Kanaklata','et.eros@Crasconvallis.com','M','04-Oct-1964','823789','Berhampore','India','West Bengal','NONE','ZTE');
INSERT INTO USER_DIM VALUES (57,'Kirsten','libero@eleifendnondapibus.com','F','17-Jul-1971','60861-825','Fortaleza','Brazil','CE','VISA','CROSSCALL');
INSERT INTO USER_DIM VALUES (58,'Wanda','non.lorem@vitae.edu','F','24-Sep-1973','H72 2VQ','Newtown','United Kingdom','MG','GIFT CARD','HONOR');
INSERT INTO USER_DIM VALUES (59,'Cheyenne','purus@idmagna.net','F','27-Aug-1995','R2E 3W8','Beausejour','Canada','Manitoba','NONE','XIAOMI');
INSERT INTO USER_DIM VALUES (60,'Autumn','cursus.et@netus.co.uk','F','21-Feb-1975','339138','Awka','Nigeria','AN','GIFT CARD','CROSSCALL');
INSERT INTO USER_DIM VALUES (61,'Kirsten','scelerisque@etcommodo.org','F','03-Apr-1976','82023-372','Londrina','Brazil','PR','AMERICAN EXPRESS','NOKIA');
INSERT INTO USER_DIM VALUES (62,'Callum','malesuada@erat.net','M','05-Jun-1987','NY3 5XV','Maidenhead','United Kingdom','BR','VISA','BQ');
INSERT INTO USER_DIM VALUES (63,'Arthur','sem@vulputatevelit.net','F','16-Apr-2009','47161','Aubervilliers','France','Île-de-France','GIFT CARD','CONDOR');
INSERT INTO USER_DIM VALUES (64,'Indigo','massa.Mauris.vestibulum@orciPhasellus.edu','M','06-Aug-1980','56688','Remscheid','Germany','NW','AMERICAN EXPRESS','CONDOR');
INSERT INTO USER_DIM VALUES (65,'Rhoda','purus.accumsan@felisDonectempor.org','F','07-Nov-1974','47993','Plauen','Germany','Saxony','MASTERCARD','ARCHOS');
INSERT INTO USER_DIM VALUES (66,'Teegan','Quisque.imperdiet@tristique.net','M','27-Oct-2005','73387','Berlin','Germany','Berlin','GIFT CARD','ASUS');
INSERT INTO USER_DIM VALUES (67,'Leonard','pellentesque@mitempor.co.uk','M','15-Jan-2003','A5X 6KD','Wrexham','United Kingdom','Denbighshire','NONE','NONE');
INSERT INTO USER_DIM VALUES (68,'Honorato','massa.Vestibulum@libero.co.uk','F','04-Mar-2001','61771','Bamberg','Germany','Bavaria','VISA','LG');
INSERT INTO USER_DIM VALUES (69,'Kylan','accumsan@Duis.edu','F','02-Sep-1977','32468','Portland','United States','Oregon','AMERICAN EXPRESS','HTC');
INSERT INTO USER_DIM VALUES (70,'Hop','rhoncus@Maurisblanditenim.net','M','26-Sep-1976','5228','Westmeerbeek','Belgium','Antwerpen','AMERICAN EXPRESS','ONEPLUS');
INSERT INTO USER_DIM VALUES (71,'Sybill','arcu.Vestibulum@feugiatplacerat.net','F','12-Sep-1974','UZ6K 4SK','Torquay','United Kingdom','Devon','AMERICAN EXPRESS','ZTE');
INSERT INTO USER_DIM VALUES (72,'Henrik','ac.facilisis.facilisis@velvulputateeu.co.uk','M','25-Mar-1986','39202','Sandviken','Sweden','X','MASTERCARD','DORO');
INSERT INTO USER_DIM VALUES (73,'Reagan','a@estconguea.co.uk','F','16-Apr-2009','2578','Sint-Martens-Bodegem','Belgium','VB','GIFT CARD','CROSSCALL');
INSERT INTO USER_DIM VALUES (74,'Apolo','tempus.eu.ligula@sapien.co.uk','M','17-Feb-1974','990415','Canela','Chile','IV','VISA','SAMSUNG');
INSERT INTO USER_DIM VALUES (75,'Donna','ipsum@lacusCrasinterdum.co.uk','M','15-Jul-1984','58401-555','João Pessoa','Brazil','Paraíba','NONE','CONDOR');
INSERT INTO USER_DIM VALUES (76,'Imogene','molestie.sodales.Mauris@quistristiqueac.edu','M','10-Nov-1977','8122','Ukkel','Belgium','Brussels Hoofdstedelijk Gewest','NONE','HONOR');
INSERT INTO USER_DIM VALUES (77,'Quentin','tincidunt.orci.quis@metusAliquamerat.edu','F','21-Sep-1980','486214','Dutse','Nigeria','Jigawa','MASTERCARD','ONEPLUS');
INSERT INTO USER_DIM VALUES (78,'Frances','enim.Sed@ipsum.org','F','24-Jul-1979','I0A 9WP','Kilsyth','United Kingdom','Stirlingshire','AMERICAN EXPRESS','MEIZU');
INSERT INTO USER_DIM VALUES (79,'Kalash','odio@Aliquamadipiscinglobortis.com','M','13-Jun-1965','464199','Delhi','India','DL','MASTERCARD','IPHONE');
INSERT INTO USER_DIM VALUES (80,'Allistair','Nam.interdum.enim@etmagnis.co.uk','M','01-Aug-1985','5071','Etterbeek','Belgium','BU','AMERICAN EXPRESS','LG');
INSERT INTO USER_DIM VALUES (81,'Carissa','dolor.tempus.non@Suspendisse.com','M','17-Oct-1983','58829-134','Sousa','Brazil','Paraíba','GIFT CARD','NOKIA');
INSERT INTO USER_DIM VALUES (82,'Rouse','at.pede@lacusQuisque.com','F','01-May-2007','535717','Paillaco','Chile','Los Ríos','VISA','ARCHOS');
INSERT INTO USER_DIM VALUES (83,'Ishmael','sed.leo@nonegestasa.org','M','30-Mar-1974','8304','Vorst','Belgium','BU','MASTERCARD','BLACKBERRY');
INSERT INTO USER_DIM VALUES (84,'Abra','non.justo.Proin@ametorciUt.net','M','14-Apr-1970','21506','Quesada','Costa Rica','Alajuela','MASTERCARD','WIKO');
INSERT INTO USER_DIM VALUES (85,'Noel','eleifend.egestas.Sed@pedeNuncsed.org','M','15-Dec-1978','042874','Coelemu','Chile','VII','AMERICAN EXPRESS','ASUS');
INSERT INTO USER_DIM VALUES (86,'Barrett','dignissim.Maecenas.ornare@euismodurnaNullam.co.uk','M','05-Nov-1967','51412','Getafe','Spain','Madrid','GIFT CARD','MOTOROLA');
INSERT INTO USER_DIM VALUES (87,'Märta','nascetur@nulla.co.uk','F','01-Oct-2004','76591','Sandviken','Sweden','Gävleborgs län','AMERICAN EXPRESS','BQ');
INSERT INTO USER_DIM VALUES (88,'Rahim','vitae@Sed.com','F','27-Mar-1991','49867','Knoxville','United States','Tennessee','NONE','SAMSUNG');
INSERT INTO USER_DIM VALUES (89,'Dillon','tempor.erat@vitaeorci.ca','M','10-May-1964','75875','Des Moines','United States','Iowa','AMERICAN EXPRESS','HONOR');
INSERT INTO USER_DIM VALUES (90,'Anaïs','Nam.nulla.magna@egestashendreritneque.co.uk','M','15-Aug-1965','98687','Sète','France','LA','VISA','IPHONE');
INSERT INTO USER_DIM VALUES (91,'Cameron','Sed.molestie.Sed@Maurismolestie.org','M','08-Jan-2002','E6Z 0J3','Fredericton','Canada','New Brunswick','AMERICAN EXPRESS','NONE');
INSERT INTO USER_DIM VALUES (92,'Yardley','Sed.congue.elit@eu.com','F','25-Mar-1988','X5K 3J8','Arviat','Canada','Nunavut','AMERICAN EXPRESS','XIAOMI');
INSERT INTO USER_DIM VALUES (93,'Aline','Quisque.purus.sapien@etrutrum.ca','F','05-May-1977','036934','Los Muermos','Chile','X','VISA','NOKIA');
INSERT INTO USER_DIM VALUES (94,'Carissa','eu@odio.ca','M','16-Oct-2002','39561','Oviedo','Spain','AS','AMERICAN EXPRESS','HONOR');
INSERT INTO USER_DIM VALUES (95,'Nissim','ultricies.ligula.Nullam@eu.edu','F','27-Oct-2005','4618','Borchtlombeek','Belgium','Vlaams-Brabant','GIFT CARD','HUAWEI');
INSERT INTO USER_DIM VALUES (96,'Kanaklata','In.mi.pede@eget.net','F','07-Oct-1981','465320','Rajahmundry','India','AP','MASTERCARD','CROSSCALL');
INSERT INTO USER_DIM VALUES (97,'Tanner','urna.justo.faucibus@duiaugue.org','M','07-Mar-1988','76730-113','Anápolis','Brazil','Goiás','NONE','XIAOMI');
INSERT INTO USER_DIM VALUES (98,'Liberty','et.magnis@bibendumDonecfelis.org','F','08-May-1998','424866','Maiduguri','Nigeria','BO','GIFT CARD','ONEPLUS');
INSERT INTO USER_DIM VALUES (99,'Akhila','mollis@velpedeblandit.org','M','13-Sep-1982','898714','Daman','India','Daman and Diu','MASTERCARD','WIKO');
INSERT INTO USER_DIM VALUES (100,'Angela','eu.metus.In@fermentumvelmauris.net','M','23-Mar-2009','99285','Idaho Falls','United States','Idaho','NONE','SAMSUNG');
